version: "3.8"

services:
  laravel-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
      - backend

  mysql-app:
    image: mysql:latest
    ports:
      - "3308:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: controle-pagamentos
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
  
networks:
  backend:
    driver: bridge
    

    